class_name LocalMapData

## 48×48 tile grid for one world tile at local (battle / city) resolution.
## Generated by LocalMapGenerator from a RegionData. Never cached.
## Also used as the base layer for BattleScene.

const SCALE: int  = 6   ## local tiles per region-tile edge
const WIDTH:  int = RegionData.SCALE * SCALE   ## = 48
const HEIGHT: int = RegionData.SCALE * SCALE   ## = 48

var world_tile: Vector2i = Vector2i.ZERO
var width:  int = WIDTH
var height: int = HEIGHT

var terrain:   Array   ## WorldData.TerrainType int
var elevation: Array   ## int 0..10  — discrete height steps
var feature:   Array   ## LocalFeature int
var passable:  Array   ## bool — pre-computed for pathfinding


enum LocalFeature {
	NONE,
	TREE,
	DENSE_TREE,
	BOULDER,
	WATER_SHALLOW,
	WATER_DEEP,
	WALL,
	DOOR,
	FLOOR,
}


func _init(wx: int = 0, wy: int = 0) -> void:
	world_tile = Vector2i(wx, wy)
	terrain   = _make(WIDTH, HEIGHT, int(WorldData.TerrainType.PLAINS))
	elevation = _make(WIDTH, HEIGHT, 0)
	feature   = _make(WIDTH, HEIGHT, int(LocalFeature.NONE))
	passable  = _make(WIDTH, HEIGHT, true)


static func _make(w: int, h: int, v: Variant) -> Array:
	var g: Array = []
	g.resize(h)
	for y in range(h):
		var row: Array = []
		row.resize(w)
		row.fill(v)
		g[y] = row
	return g
