## RegionCell — P1-01 data model for one strategic map tile.
##
## This is a plain data class. It is stored in WorldState.world_tiles
## keyed by "x,y" string (e.g. "12,4"). Never owned by a scene.
##
## Field design follows the dev plan spec plus the terrain/biome data
## loaded from /data/world/*.json.
class_name RegionCell
extends RefCounted

# ── Identity ──────────────────────────────────────────────────────────────────
var cell_id:     String = ""    # "x,y" canonical key
var grid_x:      int    = 0
var grid_y:      int    = 0

# ── Terrain fundamentals ─────────────────────────────────────────────────────
var terrain_type: String = "plains"  # content registry ID
var biome:        String = "grassland"
var elevation:    float  = 0.5      # 0.0–1.0 normalised altitude
var temperature:  float  = 0.5      # 0.0–1.0 normalised (0=cold, 1=hot)
var precipitation: float = 0.5      # 0.0–1.0 normalised
var drainage:     float  = 0.5      # 0.0–1.0 (proxy for river flux)
var prosperity:   float  = 0.0      # derived fertility score
var settlement_score: float = 0.0   # computed by settlement scorer

# ── Water features ────────────────────────────────────────────────────────────
var is_water:  bool = false
var is_river:  bool = false
var is_lake:   bool = false
var is_coast:  bool = false

# ── Land area (populated after generation) ───────────────────────────────────
var total_acres:  int = 0
var arable_acres: int = 0

# ── Resources ────────────────────────────────────────────────────────────────
## List of resource tag strings (e.g. "iron_ore", "timber", "fertile_soil").
## These drive ContentRegistry lookups for production recipes.
var resource_tags: Array[String] = []

# ── Province / political ──────────────────────────────────────────────────────
var province_id: int = -1

# ── Features ─────────────────────────────────────────────────────────────────
## Optional feature string from the feature-roll pass (e.g. "ruins", "ford").
var feature: String = ""

# ── Building placement (P3-06) ─────────────────────────────────────────────────────
## ID of the building template (from data/buildings/*.json) stamped here.
## Empty string means no building (open land, wilderness).
var building_id: String = ""

## Settlement ID that owns this cell's territory. Empty = unclaimed.
var owner_settlement_id: String = ""

## Per-floor data. Index 0 = ground, 1 = upper, -1 = cellar (stored as index 2).
## Each element is a Dictionary of floor-specific state (generated by LocalView).
## Empty until the local layer is realized (P4-01).
var z_levels: Array = []


# ── Helpers ───────────────────────────────────────────────────────────────────

func is_land() -> bool:
	return not is_water


func can_settle() -> bool:
	return is_land() and not is_river and not is_lake


# ── Serialisation ─────────────────────────────────────────────────────────────

func to_dict() -> Dictionary:
	return {
		"cell_id":          cell_id,
		"grid_x":           grid_x,
		"grid_y":           grid_y,
		"terrain_type":     terrain_type,
		"biome":            biome,
		"elevation":        elevation,
		"temperature":      temperature,
		"precipitation":    precipitation,
		"drainage":         drainage,
		"prosperity":       prosperity,
		"settlement_score": settlement_score,
		"is_water":         is_water,
		"is_river":         is_river,
		"is_lake":          is_lake,
		"is_coast":         is_coast,
		"total_acres":      total_acres,
		"arable_acres":     arable_acres,
		"resource_tags":    resource_tags.duplicate(),
		"province_id":      province_id,
		"feature":          feature,
		"building_id":      building_id,
		"owner_settlement_id": owner_settlement_id,
		"z_levels":         z_levels.duplicate(true),
	}


static func from_dict(d: Dictionary) -> RegionCell:
	var c := RegionCell.new()
	c.cell_id          = d.get("cell_id",          "")
	c.grid_x           = d.get("grid_x",           0)
	c.grid_y           = d.get("grid_y",           0)
	c.terrain_type     = d.get("terrain_type",     "plains")
	c.biome            = d.get("biome",            "grassland")
	c.elevation        = d.get("elevation",        0.5)
	c.temperature      = d.get("temperature",      0.5)
	c.precipitation    = d.get("precipitation",    0.5)
	c.drainage         = d.get("drainage",         0.5)
	c.prosperity       = d.get("prosperity",       0.0)
	c.settlement_score = d.get("settlement_score", 0.0)
	c.is_water         = d.get("is_water",         false)
	c.is_river         = d.get("is_river",         false)
	c.is_lake          = d.get("is_lake",          false)
	c.is_coast         = d.get("is_coast",         false)
	c.total_acres      = d.get("total_acres",      0)
	c.arable_acres     = d.get("arable_acres",     0)
	c.resource_tags    = Array(d.get("resource_tags", []), TYPE_STRING, "", null)
	c.province_id      = d.get("province_id",      -1)
	c.feature          = d.get("feature",          "")
	c.building_id      = d.get("building_id",      "")
	c.owner_settlement_id = d.get("owner_settlement_id", "")
	c.z_levels         = d.get("z_levels",         []).duplicate(true)
	return c


static func key(x: int, y: int) -> String:
	return "%d,%d" % [x, y]
